name: Build Vayu Kernel

on:
  workflow_dispatch:
    inputs:
      kernel_branch:
        description: 'Kernel branch'
        required: true
        default: '16'
        type: choice
        options:
          - 16
          - 16-ksu
          - 16-miui
          - 16-miui-ksu

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Free Disk Space 🧹
      run: |
        echo "Liberando espacio..."
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        df -h
        
    - name: Setup Build Environment 📦
      run: |
        echo "Instalando dependencias..."
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          bc bison build-essential ca-certificates ccache curl flex \
          git libelf-dev libssl-dev python3 wget zip zlib1g-dev
        
    - name: Setup ccache ⚡
      run: |
        echo "Configurando ccache..."
        mkdir -p ~/.ccache
        echo "max_size = 5G" > ~/.ccache/ccache.conf
        echo "compression = true" >> ~/.ccache/ccache.conf
        
    - name: Clone Kernel Source 📥
      run: |
        echo "Clonando kernel de Vayu..."
        git clone --depth=1 \
          https://github.com/AnymoreProject/android_kernel_vayu \
          -b ${{ inputs.kernel_branch }} kernel
        
    - name: Get Kernel Version 📋
      id: version
      run: |
        cd kernel
        VERSION=$(make kernelversion 2>/dev/null | cut -d'-' -f1)
        COMMIT=$(git rev-parse --short HEAD)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "commit=${COMMIT}" >> $GITHUB_OUTPUT
        
    - name: Download AOSP Clang (Official) 🔨
      run: |
        echo "Descargando el compilador oficial AOSP Clang..."
        mkdir -p toolchain
        wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r510928.tar.gz
        tar -xzf clang-r510928.tar.gz -C toolchain
        rm clang-r510928.tar.gz
        echo "AOSP Clang listo."
        
    - name: Build Kernel 🚀
      run: |
        cd kernel
        export ARCH=arm64
        export SUBARCH=arm64
        export KBUILD_BUILD_USER="GitHub"
        export KBUILD_BUILD_HOST="Actions"
        export PATH="$GITHUB_WORKSPACE/toolchain/bin:$PATH"
        
        make O=out vayu_defconfig
        
        make -j$(nproc --all) O=out \
             CC=clang \
             CROSS_COMPILE=aarch64-linux-gnu- \
             LD=ld.lld
        
    - name: Create Zip Package 📦
      run: |
        cd kernel/out/arch/arm64/boot
        if [ -f "Image.gz" ]; then
          mv Image.gz Image.gz-dtb
          zip -r9 Vayu-Kernel-${{ inputs.kernel_branch }}-${{ steps.version.outputs.commit }}.zip Image.gz-dtb
        else
          echo "Error: El archivo del kernel compilado no se encontró."
          exit 1
        fi
        
    - name: Upload Artifact 📤
      uses: actions/upload-artifact@v4
      with:
        name: Vayu-Kernel-${{ inputs.kernel_branch }}-${{ steps.version.outputs.commit }}
        path: kernel/out/arch/arm64/boot/*.zip
